nginx:
    image: ubikz/ubikz-docker-nginx
    links:
        - stream-scraper:stream-scraper
    ports:
        - "80:80"
        - "443:443"
stream-scraper:
    image: ubikz/stream-scraper
    links:
        - redis
    ports:
        - "8080"
redis:
    image: ubikz/ubikz-docker-redis
    ports:
        - "6379"
    volumes:
        - /srv/docker/redis:/data
