nginx:
    image: ubikz/ubikz-docker-nginx
    links:
        - stream-scraper:stream-scraper
        - redis-commander:redis-commander
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /srv/docker/nginx:/var/log/nginx
stream-scraper:
    image: ubikz/stream-scraper
    links:
        - redis
    ports:
        - "8080"
    volumes:
        - /srv/docker/stream-scraper:/var/log/stream_scraper
redis-commander:
    image: ubikz/ubikz-docker-redis-cmd
    links:
        - redis
    ports:
        - "8080"
    env_file: .redis-commander.env
redis:
    image: ubikz/ubikz-docker-redis
    ports:
        - "6379"
    volumes:
        - /srv/docker/redis:/data
